### ISSUE TITLE
Prepare basic project structure

### ISSUE THREAD

**Issue by Dewerton** [Dewerton/delivery-tool#2]
Please prepare basic project structure:
1. Main python file. Recommendations - implement project structure as here <https://github.com/Dewerton/student-project-examples/blob/python-jenkins-job-launcher/src/job_launcher/main.py>:
    1. Global try/except block with custom ApplicationException
    1. Basic logging configuration
    1. Arguments parsing
    1. Build config file parsing (see the example below)
1. setup.py and pyz build script
1. CHANGELOG.md file according https://keepachangelog.com/en/1.0.0/

Build config example:
```yaml
files:
- https://docker.bintray.io/artifactory/bintray-tools/com/jfrog/bintray/client/api/0.2/api-0.2.jar
- https://docker.bintray.io/artifactory/jfrog-cli/v1/1.0.0/jfrog-cli-linux-386/jfrog
- https://repo.jfrog.org/artifactory/jcenter-cache/1.0/com/minimalviking/deviceinfo/com.minimalviking.deviceinfo/maven-metadata.xml
docker:
- centos:7.5.1804
- ubuntu:latest
```
